---
language: ruby
bundler_args: --without development
cache: bundler
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.9.3
  - 2.1.0
script: bundle exec rake test
env:
env:
  - PUPPET_GEM_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
